// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {P256Verifier} from "../src/P256Verifier.sol";
import {SmartAccount} from "../src/SmartAccount.sol";
import {WebAuthn} from "../src/lib/WebAuthn.sol";

/**
 * The verifier against a signature made outside Solidity entirely — generated by node's
 * P-256, over a real WebAuthn envelope. If this passes, a passkey made in a browser is
 * genuinely checkable on chain, which is the claim the whole recovery story rests on.
 */
contract P256VerifierTest is Test {
    P256Verifier verifier;
    SmartAccount account;

    address entryPoint = address(0xE417);
    uint256 ownerKey = 0xA11CE;
    address owner;

    bytes32 constant CHALLENGE = 0x1111111111111111111111111111111111111111111111111111111111111111;
    bytes constant AUTH_DATA = hex"16ddd08ef7eec6ace452dd9eef81d2aaf4fc1706147e3c46e8800286aff178950500000001";
    string constant CLIENT_JSON =
        '{"type":"webauthn.get","challenge":"ERERERERERERERERERERERERERERERERERERERERERE","origin":"https://yuin.dev","crossOrigin":false}';
    bytes32 constant MESSAGE = 0xea9da8c1c3003a0b36a950922877bf597c717fd8b1db24a5ab5a9c909cf99210;
    uint256 constant X = 0x3c7e5d376cd88f13a07276949532b2a016a64e3de04af857eaeaa6c3bbf8fd13;
    uint256 constant Y = 0x6f62baca34aa5261d8829df8974dfc951c44d5ae7c66fdb8603133ea3e0214a2;
    uint256 constant R = 0x326bf04400a8071481512bd08db5657bf40bf6fcb37dda77e10d4a2bd19ef8b4;
    uint256 constant S = 0x673325994e163a7234b08dcba21471f6b5d96be5793e92acbc58d66fd025ccfa;

    bytes32 constant CREDENTIAL = keccak256("credential-one");

    function setUp() public {
        owner = vm.addr(ownerKey);
        verifier = new P256Verifier();
        account = new SmartAccount(entryPoint, address(0x9009), owner);

        vm.startPrank(owner);
        account.addPasskey(CREDENTIAL, X, Y);
        account.setP256Verifier(address(verifier));
        vm.stopPrank();
    }

    function callVerifier(bytes32 h, uint256 r, uint256 s, uint256 x, uint256 y) internal view returns (uint256) {
        (bool ok, bytes memory out) = address(verifier).staticcall(abi.encodePacked(h, r, s, x, y));
        assertTrue(ok, "the verifier must not revert");
        return abi.decode(out, (uint256));
    }

    function test_a_real_signature_verifies() public view {
        assertEq(callVerifier(MESSAGE, R, S, X, Y), 1);
    }

    function test_a_tampered_message_does_not() public view {
        assertEq(callVerifier(keccak256("something else"), R, S, X, Y), 0);
    }

    function test_another_key_does_not() public view {
        assertEq(callVerifier(MESSAGE, R, S, X + 1, Y), 0);
    }

    function test_short_input_is_refused() public view {
        (bool ok, bytes memory out) = address(verifier).staticcall(abi.encodePacked(MESSAGE, R));
        assertTrue(ok);
        assertEq(abi.decode(out, (uint256)), 0);
    }

    /// The whole chain: a browser passkey, through the account, verified on chain.
    function test_the_account_accepts_a_real_passkey() public view {
        assertTrue(
            account.isValidPasskeySignature(
                CREDENTIAL,
                CHALLENGE,
                WebAuthn.Signature({authenticatorData: AUTH_DATA, clientDataJSON: CLIENT_JSON, r: R, s: S})
            ),
            "a passkey made in a browser must work against a real verifier"
        );
    }

    function test_the_account_refuses_the_same_signature_for_another_challenge() public view {
        assertFalse(
            account.isValidPasskeySignature(
                CREDENTIAL,
                keccak256("a different operation"),
                WebAuthn.Signature({authenticatorData: AUTH_DATA, clientDataJSON: CLIENT_JSON, r: R, s: S})
            )
        );
    }
}
